packages:
  - packages/app-lite
  - packages/appserver
  - packages/docs
  - packages/appserver-admin
  - packages/design
  - packages/sdk
  - packages/discord-bridge
  - packages/cli
  - packages/tsconfig

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - cbor-extract
  - core-js
  - esbuild
  - node

patchedDependencies:
  "@discordeno/gateway": patches/@discordeno__gateway.patch
