-- Roomy global SQLite schema (data/global.sqlite).
--
-- Cross-space data only: the `joinedSpace` / `leftSpace` membership edges
-- (head = user DID, tail = space DID). All other edge labels (member, admin,
-- author, link, reply, forward, ...) live in the per-space DBs.
--
-- The global DB is derived data: it can be regenerated by copying
-- `joinedSpace`/`leftSpace` edges from the monolithic DB (Phase 1 lazy
-- backfill) or by replaying the local event log. Deleting it is part of the
-- Phase 1 rollback plan.

pragma foreign_keys = on;

create table if not exists global_schema_version (
  id integer primary key check (id = 1),
  version text not null
) strict;

create table if not exists edges (
  head text not null, -- user did
  tail text not null, -- space did
  label text not null, -- 'joinedSpace' | 'leftSpace'
  payload text,
  created_at integer not null default (unixepoch() * 1000),
  updated_at integer not null default (unixepoch() * 1000),
  primary key (head, tail, label)
) strict;
create index if not exists idx_edges_label on edges(label);
create index if not exists idx_edges_label_head on edges(label, head);
create index if not exists idx_edges_label_tail on edges(label, tail);
