-- Roomy global SQLite schema (data/global.sqlite).
--
-- Cross-space data only:
--   - the `joinedSpace` / `leftSpace` membership edges (head = user DID,
--     tail = space DID). All other edge labels (member, admin, author, link,
--     reply, forward, ...) live in the per-space DBs.
--   - the global `profiles` table: the authoritative per-user Roomy profile
--     (one row per DID). The atproto collection lexicon defines a single
--     global Roomy profile per user, so profiles are NOT per-space — they
--     live here. Per-space DBs keep a denormalised copy (comp_user /
--     comp_info) for stream-scoped profiles; cross-stream authors/members
--     resolve from this table at read time (queries/profileStore.ts).
--
-- The global DB is derived data: it can be regenerated by copying
-- `joinedSpace`/`leftSpace` edges from the monolithic DB (Phase 1 lazy
-- backfill) or by replaying the local event log. Deleting it is part of the
-- Phase 1 rollback plan.

pragma foreign_keys = on;

create table if not exists global_schema_version (
  id integer primary key check (id = 1),
  version text not null
) strict;

-- Tracks asynchronous/data post-migrations separately from structural DDL.
-- A schema bump inserts its version with completed_at null; startup runs the
-- registered idempotent task and stamps completion only after the whole task
-- succeeds, so interrupted deployments retry safely.
create table if not exists global_schema_migrations (
  version text primary key,
  completed_at integer
) strict;

create table if not exists edges (
  head text not null, -- user did
  tail text not null, -- space did
  label text not null, -- 'joinedSpace' | 'leftSpace'
  payload text,
  created_at integer not null default (unixepoch() * 1000),
  updated_at integer not null default (unixepoch() * 1000),
  primary key (head, tail, label)
) strict;
create index if not exists idx_edges_label on edges(label);
create index if not exists idx_edges_label_head on edges(label, head);
create index if not exists idx_edges_label_tail on edges(label, tail);

-- Global per-user Roomy profile (authoritative). One row per DID. Populated
-- by the profile fetch path (insertProfiles / insertProfilesWithExtras) and
-- by the SetUserProfile materialiser. `getProfile` reads from here.
create table if not exists profiles (
  did text primary key,
  handle text,
  name text,
  avatar text,
  description text,
  banner text,
  pronouns text,
  website text,
  updated_at integer not null default (unixepoch() * 1000)
) strict;
create index if not exists idx_profiles_handle on profiles(handle);

-- Global entity → space index. Maps every materialised entity id (room,
-- message, ...) to the space DID that owns it. Populated during
-- materialization (Phase 3): when an `insert into entities` statement is
-- applied to a per-space DB, the same (entity_id, space_did) pair is
-- recorded here. Used by `openSpaceDbForEntity` to resolve which per-space
-- DB a room/message id lives in, replacing the monolithic DB's
-- `entities.stream_id` lookup.
create table if not exists entity_space (
  entity_id text primary key,
  space_did text not null
) strict;
create index if not exists idx_entity_space_space on entity_space(space_did);

-- Global pending-embed-links index (Phase 3). Dual-written during
-- materialization alongside the per-space `comp_embed_link` rows so the
-- centralized embed sweeper can find pending work with a single query across
-- ALL per-space DBs, instead of iterating every space DB. Each row records
-- the space DID and message id that contained the URL so the sweeper can
-- route enrichment + invalidation to the correct per-space DB and delete the
-- row once processed.
create table if not exists pending_links (
  space_did text not null,
  message_id text not null,
  url text not null,
  created_at integer not null default (unixepoch() * 1000),
  primary key (space_did, message_id, url)
) strict;
create index if not exists idx_pending_links_created on pending_links(created_at);

-- Global mentions index. One row per (mentioned DID, message). Dual-written
-- during materialization so a client subscribed to the `mentions:<did>` sync
-- topic can backfill history via `space.roomy.mention.getMentions` with a
-- single cross-space query, and so deleteMessage can resolve which DIDs a
-- deleted message mentioned. The DID is the stable ID (never the handle or
-- display name).
create table if not exists mentions (
  did text not null,          -- mentioned user DID
  message_id text not null,  -- the message that mentioned them
  space_did text not null,
  room_id text not null,
  created_at integer not null default (unixepoch() * 1000),
  primary key (did, message_id)
) strict;
create index if not exists idx_mentions_did_created on mentions(did, created_at desc);

-- Search backfill cursor (Phase 2 of search-endpoints.md). One row per
-- space, tracking how far the Qdrant backfill sweeper has walked that
-- space's messages (the cursor is the last message id, ULID-ordered, from
-- the space's per-space DB). Lives in the global DB because it is
-- cross-space state; a fresh/wipe-recreated Qdrant collection clears every
-- cursor so the full corpus is re-indexed. Additive DDL only — created
-- idempotently on any schema version.
create table if not exists search_backfill_cursor (
  space_did text primary key,
  cursor text not null,
  updated_at integer not null default (unixepoch() * 1000)
) strict;

-- Channel-federation registry. Cross-space by nature, so it lives in the
-- global DB. `space_id` is the origin space (A) whose channels are exposed;
-- `federating_space_did` is the receiving space (B). One row per (A, B).
--
-- Status transitions:
--   request   -> pending
--   respond   -> active | rejected
--   remove    -> removed   (pending/active/rejected -> removed)
--   re-request after removed -> pending
--
-- Written by the SDK federation materialisers (space.roomy.federation.*),
-- routed here by statementRouting.ts (matches `space_federations`).
create table if not exists space_federations (
  space_id text not null,            -- origin space A
  federating_space_did text not null, -- receiving space B
  status text not null check(status in ('pending','active','rejected','removed')),
  requested_by_did text not null,    -- admin of B who asked
  requested_at integer not null default (unixepoch() * 1000),
  message text,                      -- request note (A-admin visible)
  decided_by_did text,               -- admin of A who decided
  decided_at integer,
  decision_message text,             -- decision note
  primary key (space_id, federating_space_did)
) strict;
create index if not exists idx_space_fed_recv on space_federations(federating_space_did, status);
create index if not exists idx_space_fed_origin_status on space_federations(space_id, status);

-- Origin grant: A-admin-set access for a receiving space B on a channel of A.
-- Mirrors role_rooms. permission null == removed / not exposed. Grants are
-- channel-scoped: threads inherit from their parent channel (see plan §5.5),
-- so lookups for a thread use its parent channel id as the room_id.
create table if not exists federation_room_permissions (
  space_id             text not null,   -- origin space A
  federating_space_did text not null,   -- receiving space B
  room_id              text not null,   -- channel id in A
  permission           text not null check(permission in ('read','readwrite')),
  primary key (space_id, federating_space_did, room_id)
) strict;
create index if not exists idx_frp_recv on federation_room_permissions(federating_space_did, permission);
create index if not exists idx_frp_room on federation_room_permissions(room_id);

-- Receiver grant: B-admin-set access for a B member, role, or ALL B members
-- on a federated channel of A. Ceiling is the origin grant
-- (federation_room_permissions).
-- kind = 'members' (grantee = B space DID, applies to every B member)
--      | 'user'    (grantee is a B user DID)
--      | 'role'    (grantee is a B role id).
create table if not exists federation_receiver_permissions (
  space_id             text not null,   -- origin space A
  federating_space_did text not null,   -- receiving space B
  room_id              text not null,   -- channel id in A
  grantee              text not null,   -- B space DID / B user DID / B role id
  kind                 text not null check(kind in ('members','user','role')),
  permission           text not null check(permission in ('read','readwrite')),
  primary key (space_id, federating_space_did, room_id, grantee, kind)
) strict;
create index if not exists idx_frper_room on federation_receiver_permissions(room_id);
