-- Roomy global SQLite schema (data/global.sqlite).
--
-- Cross-space data only:
--   - the `joinedSpace` / `leftSpace` membership edges (head = user DID,
--     tail = space DID). All other edge labels (member, admin, author, link,
--     reply, forward, ...) live in the per-space DBs.
--   - the global `profiles` table: the authoritative per-user Roomy profile
--     (one row per DID). The atproto collection lexicon defines a single
--     global Roomy profile per user, so profiles are NOT per-space — they
--     live here. Per-space DBs keep a denormalised copy (comp_user /
--     comp_info) for stream-scoped profiles; cross-stream authors/members
--     resolve from this table at read time (queries/profileStore.ts).
--
-- The global DB is derived data: it can be regenerated by copying
-- `joinedSpace`/`leftSpace` edges from the monolithic DB (Phase 1 lazy
-- backfill) or by replaying the local event log. Deleting it is part of the
-- Phase 1 rollback plan.

pragma foreign_keys = on;

create table if not exists global_schema_version (
  id integer primary key check (id = 1),
  version text not null
) strict;

-- Tracks asynchronous/data post-migrations separately from structural DDL.
-- A schema bump inserts its version with completed_at null; startup runs the
-- registered idempotent task and stamps completion only after the whole task
-- succeeds, so interrupted deployments retry safely.
create table if not exists global_schema_migrations (
  version text primary key,
  completed_at integer
) strict;

create table if not exists edges (
  head text not null, -- user did
  tail text not null, -- space did
  label text not null, -- 'joinedSpace' | 'leftSpace'
  payload text,
  created_at integer not null default (unixepoch() * 1000),
  updated_at integer not null default (unixepoch() * 1000),
  primary key (head, tail, label)
) strict;
create index if not exists idx_edges_label on edges(label);
create index if not exists idx_edges_label_head on edges(label, head);
create index if not exists idx_edges_label_tail on edges(label, tail);

-- Global per-user Roomy profile (authoritative). One row per DID. Populated
-- by the profile fetch path (insertProfiles / insertProfilesWithExtras) and
-- by the SetUserProfile materialiser. `getProfile` reads from here.
create table if not exists profiles (
  did text primary key,
  handle text,
  name text,
  avatar text,
  description text,
  banner text,
  pronouns text,
  website text,
  updated_at integer not null default (unixepoch() * 1000)
) strict;
create index if not exists idx_profiles_handle on profiles(handle);

-- Global entity → space index. Maps every materialised entity id (room,
-- message, ...) to the space DID that owns it. Populated during
-- materialization (Phase 3): when an `insert into entities` statement is
-- applied to a per-space DB, the same (entity_id, space_did) pair is
-- recorded here. Used by `openSpaceDbForEntity` to resolve which per-space
-- DB a room/message id lives in, replacing the monolithic DB's
-- `entities.stream_id` lookup.
create table if not exists entity_space (
  entity_id text primary key,
  space_did text not null
) strict;
create index if not exists idx_entity_space_space on entity_space(space_did);

-- Global pending-embed-links index (Phase 3). Dual-written during
-- materialization alongside the per-space `comp_embed_link` rows so the
-- centralized embed sweeper can find pending work with a single query across
-- ALL per-space DBs, instead of iterating every space DB. Each row records
-- the space DID and message id that contained the URL so the sweeper can
-- route enrichment + invalidation to the correct per-space DB and delete the
-- row once processed.
create table if not exists pending_links (
  space_did text not null,
  message_id text not null,
  url text not null,
  created_at integer not null default (unixepoch() * 1000),
  primary key (space_did, message_id, url)
) strict;
create index if not exists idx_pending_links_created on pending_links(created_at);

-- Global mentions index. One row per (mentioned DID, message). Dual-written
-- during materialization so a client subscribed to the `mentions:<did>` sync
-- topic can backfill history via `space.roomy.mention.getMentions` with a
-- single cross-space query, and so deleteMessage can resolve which DIDs a
-- deleted message mentioned. The DID is the stable ID (never the handle or
-- display name).
create table if not exists mentions (
  did text not null,          -- mentioned user DID
  message_id text not null,  -- the message that mentioned them
  space_did text not null,
  room_id text not null,
  created_at integer not null default (unixepoch() * 1000),
  primary key (did, message_id)
) strict;
create index if not exists idx_mentions_did_created on mentions(did, created_at desc);
