/**
 * Model-based test driver: spec oracle ↔ src/auth/access.ts parity.
 *
 * Workflow (see specs/auth.qnt and specs/README.md):
 *   1. Generate traces:
 *        pnpm --filter @roomy/appserver mbt:traces
 *      (pins quint 0.32.0 + the seed; traces land in specs/traces/, which is
 *      gitignored — they are generated artefacts, not sources.)
 *   2. Run this test file. For every state in every trace we:
 *      - build a fresh in-memory SQLite DB,
 *      - project the spec state (and *only* that) into the DB,
 *      - call spaceAccess()/roomAccess() and compare each field-by-field
 *        against the trace's oracleSnapshot.
 *
 * Both read paths into the room_access projection are driven: the single-room
 * `roomAccess()` path, and the batched `roomAccessMany()` path the sidebar /
 * getThreads handlers use. The first touch of each is a cold miss (live
 * compute, then warm the projection); the second is a projection hit.
 *
 * One bun test per trace file. State index is included in failure messages.
 */

import { describe, test, expect } from "bun:test";
import { Database } from "bun:sqlite";
import { toAsyncDb } from "../../db/syncAdapter.ts";
import type { DbLike } from "../../db/types.ts";
import { existsSync, readdirSync, readFileSync } from "fs";
import { join, dirname, resolve } from "path";
import { fileURLToPath } from "url";

import { parseTrace } from "./itf.ts";
import {
  permissionToString,
  type SpecRoomAccess,
  type SpecSpaceAccess,
  type SpecVars,
} from "./types.ts";
import { project, SPACE_ID } from "./project.ts";
import {
  roomAccess,
  roomAccessMany,
  spaceAccess,
  type RoomAccess,
  type SpaceAccess,
} from "../access.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SCHEMA_PATH = join(__dirname, "..", "..", "db", "schema.sql");
const SCHEMA_VERSION = "10-appserver.4";

function freshDb(): { db: Database; asyncDb: DbLike } {
  const db = new Database(":memory:");
  db.exec("pragma journal_mode = wal");
  db.exec("pragma synchronous = normal");
  db.exec("pragma foreign_keys = on");
  const schemaSql = readFileSync(SCHEMA_PATH, "utf8");
  db.exec(schemaSql);
  db.run("insert into roomy_schema_version (id, version) values (1, ?)", [
    SCHEMA_VERSION,
  ]);
  return { db, asyncDb: toAsyncDb(db) };
}

const TRACES_DIR = resolve(import.meta.dir, "../../../specs/traces");

function listTraces(): string[] {
  if (!existsSync(TRACES_DIR)) return [];
  return readdirSync(TRACES_DIR)
    .filter((f) => f.endsWith(".itf.json"))
    .sort();
}

function expectedRoomAccess(s: SpecRoomAccess): RoomAccess {
  return {
    exists: s.exists,
    canRead: s.canRead,
    canWrite: s.canWrite,
    isAdmin: s.isAdmin,
    isBanned: s.isBanned,
    defaultAccess: permissionToString(s.defaultAccess),
    // The impl returns spaceId=null when the room doesn't exist, otherwise
    // the SPACE DID. The harness uses a single space, so this is constant.
    spaceId: s.exists ? SPACE_ID : null,
    parentChannelId:
      s.parentChannel.tag === "HasParent"
        ? (s.parentChannel.value as string)
        : null,
  };
}

function expectedSpaceAccess(s: SpecSpaceAccess): SpaceAccess {
  return {
    isMember: s.isMember,
    isAdmin: s.isAdmin,
    isBanned: s.isBanned,
  };
}

const traceFiles = listTraces();

describe("MBT: spec oracle ↔ access.ts parity", () => {
  if (traceFiles.length === 0) {
    // Traces are generated by quint, which is not a dependency of this repo
    // (and needs no Java — the simulator emits the traces). Failing the suite
    // here would keep it permanently red and train contributors to ignore
    // failures. Skip instead — the message is preserved in the skipped-test
    // output so the reminder isn't lost. CI generates traces before `bun test`,
    // so this branch is a local-development convenience, not the CI path.
    const howTo =
      `no .itf.json files in ${TRACES_DIR}. Generate with:\n` +
      `  pnpm --filter @roomy/appserver mbt:traces`;
    console.warn(`[MBT] ${howTo}`);
    test.skip(`no trace files found — run 'pnpm --filter @roomy/appserver mbt:traces'`, () => {});
    return;
  }

  for (const file of traceFiles) {
    test(file, async () => {
      const raw = JSON.parse(readFileSync(`${TRACES_DIR}/${file}`, "utf8"));
      const trace = parseTrace<SpecVars>(raw);

      for (const stateEntry of trace.states) {
        const { db, asyncDb } = freshDb();
        try {
          project(db, stateEntry.vars.state);

          const ctx = `${file} state[${stateEntry.index}] action=${stateEntry.actionTaken}`;

          // The batched path the sidebar / getThreads handlers use, driven over
          // exactly the room ids in this snapshot. `roomAccessMany` carries its
          // own copy of the decision logic (it batches the lookups for
          // efficiency), so it can drift from the spec independently of the
          // single-room path — and from `computeRoomAccess`, which its own
          // docstring claims it stays in parity with.
          // `oracleSnapshot.rooms` is a tuple-keyed map: [[userId, roomId], access].
          const roomIds = [
            ...new Set(
              stateEntry.vars.oracleSnapshot.rooms.map(([[, rid]]) => rid),
            ),
          ];
          const users = [
            ...new Set(
              stateEntry.vars.oracleSnapshot.rooms.map(([[uid]]) => uid),
            ),
          ];

          for (const uid of users) {
            const batched = await roomAccessMany(asyncDb, roomIds, uid);
            // Every requested room must come back — a silently short map would
            // otherwise skip the comparisons below and pass vacuously.
            expect(batched.size).toBe(roomIds.length);
            for (const rid of roomIds) {
              const expected = stateEntry.vars.oracleSnapshot.rooms.find(
                ([[u, r]]) => u === uid && r === rid,
              )?.[1];
              if (expected === undefined) continue;
              const got = batched.get(rid);
              const want = expectedRoomAccess(expected);
              try {
                expect(got).toEqual(want);
              } catch {
                throw new Error(
                  `[${ctx}] roomAccessMany mismatch for (${uid}, ${rid})\n` +
                    `  got:  ${JSON.stringify(got)}\n` +
                    `  want: ${JSON.stringify(want)}`,
                );
              }
            }
          }

          // spaceAccess parity over every user in the snapshot.
          for (const [uid, expected] of stateEntry.vars.oracleSnapshot.spaces) {
            const got = await spaceAccess(asyncDb, SPACE_ID, uid);
            const want = expectedSpaceAccess(expected);
            try {
              expect(got).toEqual(want);
            } catch (e) {
              throw new Error(
                `[${ctx}] spaceAccess mismatch for ${uid}\n` +
                  `  got:  ${JSON.stringify(got)}\n` +
                  `  want: ${JSON.stringify(want)}`,
              );
            }
          }

          // roomAccess parity over every (user, room) in the snapshot.
          for (const [[uid, rid], expected] of stateEntry.vars.oracleSnapshot
            .rooms) {
            const got = await roomAccess(asyncDb, rid, uid);
            const want = expectedRoomAccess(expected);
            try {
              expect(got).toEqual(want);
            } catch (e) {
              throw new Error(
                `[${ctx}] roomAccess mismatch for (${uid}, ${rid})\n` +
                  `  got:  ${JSON.stringify(got)}\n` +
                  `  want: ${JSON.stringify(want)}`,
              );
            }
          }
        } finally {
          asyncDb.close();
        }
      }
    });
  }
});
